# Generated by Django 3.1.5 on 2021-01-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadordetail',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
