# Generated by Django 3.1.5 on 2021-01-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caportal', '0002_ambassadordetail_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadordetail',
            name='score',
            field=models.IntegerField(),
        ),
    ]
