# Generated by Django 3.1.5 on 2021-01-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caportal', '0005_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='points',
            new_name='max_points',
        ),
        migrations.AddField(
            model_name='task',
            name='points_awarded',
            field=models.IntegerField(default=0),
        ),
    ]
