# Generated by Django 3.1.5 on 2021-01-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caportal', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='by_manager',
            field=models.BooleanField(default=False),
        ),
    ]
