# Generated by Django 3.1.5 on 2021-02-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=200)),
                ('institute', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('domain', models.CharField(choices=[('PR', 'krati@elan.org.in'), ('Sponsorship', 'ashutosh.t@elan.org.in'), ('Shows', 'adyasa.m@elan.org.in'), ('Workshop', 'mahesh.s@elan.org.in'), ('Culti', 'sharanya@elan.org.in'), ('Biggies', 'sharanya@elan.org.in'), ('Techy', 'mahesh.s@elan.org.in'), ('Social Cause', 'sharanya@elan.org.in'), ('Informals', 'krati@elan.org.in'), ('Miscellaneous', 'info@elan.org.in'), ('Finance', 'finance.head@elan.org.in'), ('Merch', 'finance.head@elan.org.in')], max_length=45)),
            ],
        ),
    ]
