# Generated by Django 3.1.5 on 2021-02-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetail',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='contactdetail',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='contactdetail',
            name='institute',
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='message',
            field=models.CharField(default='nothing...', max_length=500),
            preserve_default=False,
        ),
    ]
