# Generated by Django 3.1.5 on 2021-02-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20210207_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELANRegisteration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('institute', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='domain',
            field=models.CharField(choices=[('PR', 'PR'), ('Sponsorship', 'Sponsorship'), ('Shows', 'Shows'), ('Workshop', 'Workshop'), ('Culti', 'Culti'), ('Biggies', 'Biggies'), ('Techy', 'Techy'), ('Social Cause', 'Social Cause'), ('Informals', 'Informals'), ('Miscellaneous', 'Miscellaneous'), ('Finance', 'Finance'), ('Merch', 'Merch')], max_length=45),
        ),
    ]
