# Generated by Django 3.1.5 on 2021-02-10 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20210210_0337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ELANRegisteration',
            new_name='ELANRegistration',
        ),
    ]
