# Generated by Django 3.1.5 on 2021-02-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20210210_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elanregistration',
            name='phone',
        ),
        migrations.AddField(
            model_name='elanregistration',
            name='email',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elanregistration',
            name='institute',
            field=models.CharField(max_length=50),
        ),
    ]
